import {
  faArrowUpRightFromSquare, faAt,
  faBackward, faBan,
  faBarsProgress, faBell, faBook,
  faCalendar,
  faCalendarDay,
  faCalendarDays, faCalendarXmark, faCaretSquareUp, faCertificate, faChartGantt, faCheckCircle, faCircleInfo,
  faClock, faCrown, faEarthAmericas, faFilter, faForward,
  faGift, faHandHoldingHeart, faHandSparkles, faHashtag,
  faHourglass, faKey, faLink, faLocationPin, faLock, faMagnifyingGlass, faMedal, faMessage, faMoon, faPause,
  faPeopleGroup, faPlusCircle, faRightFromBracket, faRightToBracket, faServer, faShareNodes,
  faShuffle, faSignsPost, faStar, faTableColumns, faTag, faTrophy, faUser,
  faWrench, faXmark
} from "@fortawesome/free-solid-svg-icons";
import {
  faDiscord,
  faFacebook,
  faInstagram,
  faLinkedin,
  faRedditAlien,
  faTiktok, faTwitch,
  faXTwitter,
  faYoutube
} from "@fortawesome/free-brands-svg-icons";

export const icons = {

  /* app-specific terms */
  trade: faShuffle,
  volunteers: faPeopleGroup,
  rewards: faGift,
  rewardsAlt: faHandHoldingHeart,
  schedule: faBarsProgress,
  event: faStar,
  activity: faStar,
  location: faLocationPin,
  invite: faMessage,
  inviteActive: faCertificate,
  inviteInactive: faLock,
  userType: faUser,
  role: faHashtag,
  signUp: faKey,
  signedUp: faCertificate,
  signupRequested: faRightToBracket,
  assigned: faCheckCircle,
  unassigned: faBan,
  requestedUnassign: faRightFromBracket,
  eligible: faCertificate,
  ineligible: faBan,
  plan: faTableColumns,
  phase: faChartGantt,
  leaderboard: faTrophy,
  leaderboardFirst: faCrown,
  leaderboardPodium: faMedal,
  leaderboardOther: faCertificate,
  position: faWrench,
  shift: faHandSparkles,
  rewardShare: faShareNodes,
  pretalxKey: faKey,
  pretalxHost: faServer,
  email: faAt,
  timeConflict: faCalendarXmark,

  /* labels */
  calendar: faCalendar,
  manage: faWrench,
  name: faTag,
  shortDescription: faCircleInfo,
  longDescription: faBook,
  description: faCircleInfo,
  unavailable: faPause,
  create: faPlusCircle,
  limit: faCaretSquareUp,
  count: faHashtag,
  url: faLink,
  noEdit: faLock,
  filter: faFilter,
  notification: faBell,
  noNotification: faMoon,
  info: faCircleInfo,
  help: faSignsPost,
  expand: faArrowUpRightFromSquare,
  close: faXmark,
  link: faLink,
  empty: faMagnifyingGlass,

  /* time */
  hour: faHourglass,
  day: faCalendarDay,
  date: faCalendarDays,
  startDate: faForward,
  endDate: faBackward,
  expiry: faClock,

  /* socials */
  reddit: faRedditAlien,
  discord: faDiscord,
  twitter: faXTwitter,
  facebook: faFacebook,
  instagram: faInstagram,
  linkedIn: faLinkedin,
  youtube: faYoutube,
  tiktok: faTiktok,
  twitch: faTwitch,
  website: faEarthAmericas
};
