/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from NotificationService.Classes.Dto.PushNotificationEventDto */
export type PushNotificationEventDto = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string */
    notification: string;
    /** Transpiled from System.DateTime */
    time: (Date | string);
    /** Transpiled from string? */
    url?: string;
}

