/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from NotificationService.Classes.Dto.TestEventDto */
export type TestEventDto = {
    /** Transpiled from string */
    message: string;
}

