/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from NotificationService.Classes.Dto.TestEvent */
export type TestEvent = {
    /** Transpiled from string */
    message: string;
}

