/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IPushNotificationHub, IPushNotificationHubReceiver } from './NotificationService.Hubs';
import type { PushNotificationEventDto } from '../NotificationService.Classes.Dto';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IPushNotificationHub"): HubProxyFactory<IPushNotificationHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IPushNotificationHub") {
        return IPushNotificationHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IPushNotificationHubReceiver"): ReceiverRegister<IPushNotificationHubReceiver>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IPushNotificationHubReceiver") {
        return IPushNotificationHubReceiver_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IPushNotificationHub_HubProxyFactory implements HubProxyFactory<IPushNotificationHub> {
    public static Instance = new IPushNotificationHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IPushNotificationHub => {
        return new IPushNotificationHub_HubProxy(connection);
    }
}

class IPushNotificationHub_HubProxy implements IPushNotificationHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly getPendingNotifications = async (): Promise<PushNotificationEventDto[]> => {
        return await this.connection.invoke("GetPendingNotifications");
    }
}


// Receiver

class IPushNotificationHubReceiver_Binder implements ReceiverRegister<IPushNotificationHubReceiver> {

    public static Instance = new IPushNotificationHubReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IPushNotificationHubReceiver): Disposable => {

        const __pushNotificationReceived = (...args: [PushNotificationEventDto]) => receiver.pushNotificationReceived(...args);

        connection.on("PushNotificationReceived", __pushNotificationReceived);

        const methodList: ReceiverMethod[] = [
            { methodName: "PushNotificationReceived", method: __pushNotificationReceived }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

