/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { ITestHub, ITestHubReceiver } from './NotificationService.Hubs';
import type { TestEventDto } from '../NotificationService.Classes.Dto';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "ITestHub"): HubProxyFactory<ITestHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "ITestHub") {
        return ITestHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "ITestHubReceiver"): ReceiverRegister<ITestHubReceiver>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "ITestHubReceiver") {
        return ITestHubReceiver_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class ITestHub_HubProxyFactory implements HubProxyFactory<ITestHub> {
    public static Instance = new ITestHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): ITestHub => {
        return new ITestHub_HubProxy(connection);
    }
}

class ITestHub_HubProxy implements ITestHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly sendTestEvent = async (testEventDto: TestEventDto): Promise<TestEventDto> => {
        return await this.connection.invoke("SendTestEvent", testEventDto);
    }
}


// Receiver

class ITestHubReceiver_Binder implements ReceiverRegister<ITestHubReceiver> {

    public static Instance = new ITestHubReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: ITestHubReceiver): Disposable => {

        const __testEventReceived = (...args: [TestEventDto]) => receiver.testEventReceived(...args);

        connection.on("TestEventReceived", __testEventReceived);

        const methodList: ReceiverMethod[] = [
            { methodName: "TestEventReceived", method: __testEventReceived }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

