/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { TestEvent } from '../NotificationService.Classes.Dto';

export type ITestHub = {
    /**
    * @param testEvent Transpiled from NotificationService.Classes.Dto.TestEvent
    * @returns Transpiled from System.Threading.Tasks.Task<NotificationService.Classes.Dto.TestEvent>
    */
    sendTestEvent(testEvent: TestEvent): Promise<TestEvent>;
}

export type ITestHubReceiver = {
    /**
    * @param testEvent Transpiled from NotificationService.Classes.Dto.TestEvent
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    testEventReceived(testEvent: TestEvent): Promise<void>;
}

