/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { PushNotificationEventDto } from '../NotificationService.Classes.Dto';

export type IPushNotificationHub = {
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.ICollection<NotificationService.Classes.Dto.PushNotificationEventDto>>
    */
    getPendingNotifications(): Promise<PushNotificationEventDto[]>;
}

export type IPushNotificationHubReceiver = {
    /**
    * @param notificationEvent Transpiled from NotificationService.Classes.Dto.PushNotificationEventDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    pushNotificationReceived(notificationEvent: PushNotificationEventDto): Promise<void>;
}

